export const GIT_LOCATOR_TEST_VALUES = {
  linuxPlatform: 'linux',
  macOSPlatform: 'darwin',
  windowsPlatform: 'win32',
  linuxPathEnvironment: '/custom/git/bin',
  linuxPathCandidate: '/custom/git/bin/git',
  macOSPathEnvironment: '/usr/bin',
  macOSHomeDirectory: '/Users/example',
  macOSHomebrewCandidate: '/opt/homebrew/bin/git',
  windowsProgramFiles: 'C:\\Program Files',
  windowsPathEnvironment: 'C:\\Git\\bin',
  windowsHomeDirectory: 'C:\\Users\\example',
  windowsGitCandidate: 'C:\\Program Files\\Git\\cmd\\git.exe',
  vaultPath: '/vault',
  defaultExecutable: 'git',
  customExecutablePath: '/custom/tools/git',
  missingExecutablePath: '/missing/git',
  gitVersionOutput: 'git version 2.48.1',
  nonGitVersionOutput: 'not a Git executable',
} as const;
